# Site settings
title: "Christopher Haupt's Resume"
description: "A resume for Christopher Haupt"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Christopher Haupt"
resume_title:                   "Administrator and IT Professional"
resume_contact_email:           "chris.james.haupt@gmail.com"
resume_contact_telephone:       "+447539830834"
resume_contact_address:         "Basel, Switzerland"
resume_header_contact_info: "UK +447544094789 | CN +8615158197693 | chris.james.haupt@gmail.com"
resume_header_intro: "<p>After graduating university in 2015 I earned a CELTA qualification and accepted a job to teach English in China. The scope of my work since then has included much more than planning and giving English classes. I have at various times also taught PE, Science, Drama, UOI and Film Studies. In this time I have developed several core competencies that are vital to any industry: <ul><li>Media production</li><li>Giving presentations</li><li>Mediating disputes (parent/teacher and management/employee)</li><li>Generating reports</li><li>Coping under pressure</li><li>Working to deadlines</li><li>Teamwork/collaboration</li><li>Project management</li><li>Profficiency with a variety of essential applications</li></ul> I look forward to putting these skills to use in achieving the goals of your company.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
resume_github_url:            "https://github.com/erasebegin"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "https://www.facebook.com/EraseBegin"
resume_linkedin_url:          "https://www.linkedin.com/in/chris-haupt"
  #resume_instagram_url:         "https://www.instagram.com/christhaupt/"
resume_website_url:           "http://erasebegin.github.io/necessary-products"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
